# Generated by Django 2.1.7 on 2019-08-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=150)),
                ('song_artist', models.CharField(max_length=150)),
                ('song_url', models.CharField(max_length=300)),
                ('user_email', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'user_history',
            },
        ),
        migrations.AlterUniqueTogether(
            name='song_table',
            unique_together={('song_name', 'song_artist', 'user_email')},
        ),
    ]
