# Generated by Django 2.1.7 on 2019-08-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song_table',
            unique_together=set(),
        ),
    ]
