# Generated by Django 2.1.7 on 2019-08-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20190809_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song_table',
            unique_together={('song_name', 'song_artist', 'user_email')},
        ),
    ]
